language: php

sudo: required

# Only run tests when committing to our primary branch and pull requests.
branches:
  only:
  - master

env:
  global:
  - ANSIBLE_ROLE_NAME=opendevshop.apache
  - DEVSHOP_VERSION=1.x
  - SITE_HOSTS='dev.drup.devshop.travis dev.projectname.devshop.travis live.projectname.devshop.travis testenv.drpl8.devshop.travis dev.rootproject.devshop.local.computer'

  matrix:
  - test="Ubuntu 14.04 Apache"
    COMMAND="bin/robo up --mode=install.sh --test"

  - test="Ubuntu 16.04 Apache"
    COMMAND='bin/robo up --mode=install.sh --install-sh-image=geerlingguy/docker-ubuntu1604-ansible --test'

#   - test="Ubuntu 18.04 Apache"
#     COMMAND='bin/robo up --mode=install.sh --install-sh-image=geerlingguy/docker-ubuntu1804-ansible --test'

  #  - test="Install with Ansible on Ubuntu 14.04 with NGINX"
  #    COMMAND="robo up --mode=install.sh --test --install-sh-options='--server-webserver=nginx'"

#   - test="CentOS 7"
#     COMMAND="bin/robo up --mode=install.sh --install-sh-image=geerlingguy/docker-centos7-ansible --test"

#  - test="Install with Ansible on Fedora 25"
#    COMMAND="robo up --mode=install.sh --install-sh-image=centos:7 --test"

addons:
  hosts:
  - devshop.travis
  - dev.projectname.devshop.travis
  - live.projectname.devshop.travis
  - dev.drpl8.devshop.travis
  - testenv.drpl8.devshop.travis
  - dev.rootproject.devshop.local.computer

services:
- docker

before_install:
- env
- id -u
- docker --version
- docker-compose --version

# Clone devshop
- cd ..
- git clone http://github.com/opendevshop/devshop
- cd devshop
- git checkout $DEVSHOP_VERSION

# Prepare devshop CLI.
- composer install

script:

# Run robo p:s to scaffold roles
- bin/robo p:s -n
- touch $TRAVIS_BUILD_DIR/copied
- ls -la $TRAVIS_BUILD_DIR
- cp -rf $TRAVIS_BUILD_DIR/* roles/$ANSIBLE_ROLE_NAME
- ls -la roles/$ANSIBLE_ROLE_NAME

# Copy this role into the /roles folder


# Launch devshop including preparing the source code.
- echo "Running ${COMMAND} -n --xdebug=0 ..."
- ${COMMAND} -n --disable-xdebug

notifications:
  slack: thinkdrop:pb05x3ZL3qumHs0RjqEXvYfA

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
