---
- name: Converge
  hosts: all
  become: true

  vars_files:
    - test-vars.yml

  vars:
    # Deploy from the Drupal for Kubernetes example project.
    drupal_deploy: true
    drupal_deploy_repo: "https://github.com/geerlingguy/drupal-for-kubernetes.git"
    drupal_deploy_dir: /var/www/drupal
    drupal_domain: "test.pidramble.com"

    # Disable Composer-based codebase setup.
    drupal_build_composer_project: false
    drupal_build_composer: false
    drupal_composer_dependencies: []

  pre_tasks:
    - import_tasks: test-setup.yml

  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - role: geerlingguy.repo-dotdeb
      when: ansible_distribution == 'Debian'
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.php-mysql
    - role: geerlingguy.git
    - role: geerlingguy.composer
    - role: geerlingguy.drush
    - role: geerlingguy.drupal
