---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=600
  when: ansible_os_family == 'Debian'

- name: Install dependencies.
  package:
    name:
      - curl
      - unzip
      - sendmail
