<?php

/**
 * Implements hook_hosting_service().
 */
function ansible_services_hosting_service() {
    $services = array();
    if (module_exists('hosting_site')) {
        $services['ansible_mysql'] = 'db';
        $services['ansible_apache'] = 'http';
        $services['ansible_haproxy'] = 'load';
    }
    return $services;
}

/**
 * Implements hook_hosting_service_type().
 */
function ansible_services_hosting_service_type()
{
    return array(
      'load' => array(
        'title' => t('Load Balancer'),
      ),
    );
}