<?php


/**
 * Implements hook_hosting_service().
 */
function ansible_roles_hosting_service() {

    $services['ansible_roles'] = 'ansible';
    if (module_exists('hosting_site')) {
        $services['ansible_mysql'] = 'db';
        $services['ansible_apache'] = 'http';
    }
    return $services;
}

/**
 * Implements hook_hosting_service_type().
 */
function ansible_roles_hosting_service_type()
{
    return array(
        'ansible' => array(
            'title' => t('Server Roles'),
        ),
    );
}