---
- name: Converge
  hosts: all
  become: true

  vars:
    git_install_from_source: false
    git_install_path: /usr/local

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: geerlingguy.git
