#!/usr/bin/env php
<?php

// Set to run indefinitely.
set_time_limit(0);
// Include the composer autoloader.
if (file_exists(__DIR__ . '/vendor')) {
    // Standalone installation.
    require_once __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(dirname(__DIR__) . '/vendor')) {
    // Composer global installation.
    require_once dirname(__DIR__) . '/../../vendor/autoload.php';
} else {
    echo 'You must set up the project dependencies, run the following commands:' . PHP_EOL .
        'curl -sS https://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL;
}


use DevShop\Command\Status;
use DevShop\Command\Login;
use DevShop\Command\Install;
use DevShop\Command\Upgrade;
use DevShop\Command\RemoteInstall;

use Symfony\Component\Console\Application;
use Symfony\Component\Process\Process;

$process = new Process('git symbolic-ref -q HEAD || git describe --tags --exact-match', __DIR__);
$process->run();
$version = str_replace('refs/heads/', '', $process->getOutput());

$application = new Application('DevShop CLI', $version);
$application->add(new Status());
$application->add(new Login());
$application->add(new Install());
$application->add(new Upgrade());
$application->add(new RemoteInstall());
$application->run();
