<?php
/**
 * @file devshop_hosting.module
 */
drupal_add_css(drupal_get_path('module', 'devshop_hosting') . '/devshop.css');


/**
 * Implements hook_menu()
 */
function devshop_hosting_menu(){
  $items['devshop'] = array(
    'title' => 'Welcome to DevShop',
    'page callback' => 'devshop_hosting_home',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Implements hook_menu()
 */
function devshop_hosting_menu_alter(&$items){
  $items['user/password']['type'] = MENU_CALLBACK;
  unset($items['hosting/sites']);
  unset($items['hosting/platforms']);
  
  $items['hosting/servers/add'] = $items['node/add/server'];
  $items['hosting/servers/add']['title'] = t('Add new Server');
  $items['hosting/servers/add']['type'] = MENU_LOCAL_TASK;
  $items['hosting/servers/add']['page arguments'] = array('server');
  
  $items['hosting/servers/list'] = array(
    'title' => t('All Servers'),
    'weight' => -1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
}

/**
 * Provides a login page or redirects to proejcts
 */
function devshop_hosting_home(){
  if (user_is_logged_in()){
    drupal_goto(variable_get('devshop_frontpage', 'hosting/projects'));
  } else {
    $output = '<p>' . t('Please log in.') . '</p>';
    return drupal_get_form('user_login');
  }
}

/**
 * Implements hook_form_user_login_alter()
 * Provides some UI enhancements.
 */
function devshop_hosting_form_user_login_alter(&$form){
  $form['pass']['#description'] .= '  ' . l(t('Forgot your Password?'), 'user/password');
}


/**
 * Implements hook_form_user_login_block_alter()
 * Provides some UI enhancements.
 */
function devshop_hosting_form_user_login_block_alter(&$form){
  if (arg(0) == 'devshop'){
    $form = array();
  }
}