#!/usr/bin/env php
<?php

/**
 * This file is a standalone command that allows the "yaml-tests" script to be
 * run where composer may not be installed. For example, if an artifact is built
 * from your application and vendor directories, the artifact could be deployed
 * to a server that does not have global composer installed, and you would still
 * be able to run `./bin/yaml-tests`.
 */

// Thanks to g1a/starter for providing a standard autoloader.
// If we're running from phar load the phar autoload file.
$pharPath = \Phar::running(true);
if ($pharPath) {
  $autoloaderPath = "$pharPath/vendor/autoload.php";
} else {
  if (file_exists(__DIR__.'/vendor/autoload.php')) {
    $autoloaderPath = __DIR__.'/vendor/autoload.php';
  } elseif (file_exists(__DIR__.'/../../autoload.php')) {
    $autoloaderPath = __DIR__ . '/../../autoload.php';
  } else {
    die("Could not find autoloader. Run 'composer install'.");
  }
}
$classLoader = require $autoloaderPath;

use ProvisionOps\YamlTests\Command as YamlTestsCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

$version = 'dev';
$application = new Application('yaml-tests', $version);

$command = new YamlTestsCommand();
$composer = new \Composer\Composer();

$package = new \Composer\Package\RootPackage("provision-ops/yaml-tests", $version, "Development");
$composer->setPackage($package);

$command->setComposer($composer);

$application->add($command);
$application->setDefaultCommand($command->getName(), true);

$application->run();