###
# DevShop Server Container
#
# All-in-one DevShop. Includes all services required to run on one instance.
#
# Container name: devshop/server
#
###
---
- hosts: all
  become: true

  vars:
    # Hostname must be set when container is launched, which "hostname" option.
    server_hostname: "devshop.local.computer"
    server_hostname_ignore_errors: true

    # The geerlingguy.mysql and opendevshop.devmaster roles both use this
    mysql_root_password: root

    # @TODO: Install multiple versions per-container: https://github.com/oerdnj/deb.sury.org/wiki/Managing-Multiple-Versions
    php_version: "7.2"

    php_default_version_debian: "{{ php_version }}"

    # This is set to TRUE to ensure the playbooks don't try to run the devmaster upgade every time they run (aka on robo up).
    devmaster_skip_upgrade: true

    # Use Python3.
    # @TODO: This is now set only for Debian systems, in the `pre_tasks` section below..
    # ansible_python_interpreter: python3

    # Supervisor will start when the container and systemd start.
    supervisor_started: true

  pre_tasks:
    - name: Set variables ({{ ansible_os_family}} {{ansible_distribution_major_version}})
      when:
        - ansible_os_family == 'RedHat'
        - devshop_install_phase == 'buildtime'
      set_fact:
        apache_state: stopped

    # @TODO: Remove this if ansible_python_interpreter: python3 solves it.
    # @TODO: I was unable to get ubuntu18 installs to properly detect and install the 'mysql_python_package_debian' packages.
    # https://github.com/opendevshop/devshop/pull/518/checks?check_run_id=517865257#step:7:523
    # By default, geerlingguy.mysql loads this automatically. However, in the automated tests for the role, Jeff DOES force set the variable:
    # The automated tests for geerlingguy.mysql set this variable too!
    #   https://github.com/geerlingguy/ansible-role-drupal/blob/master/molecule/default/test-vars.yml#L24
    - name: Set all Debian systems to use python3 as the interpretor, and python3-mysqldb for mysql_python_package_debian.
      when:
        - ansible_os_family == 'Debian'
      set_fact:
        mysql_python_package_debian: python3-mysqldb
        ansible_python_interpreter: python3
      tags: [mysql]

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
      tags: [geerlingguy, apache]

    - role: opendevshop.apache
      tags: [opendevshop, opendevshop.apache]

    - role: geerlingguy.apache
      tags: [geerlingguy, apache]

    - role: geerlingguy.mysql
      tags: [geerlingguy, mysql]

    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql

    - geerlingguy.composer
    - opendevshop.devmaster
