#
# DevShop Role Container Playbook Template
#
---
# The "hosts" must match the "[group_name]" entry in the inventory.
- hosts: local
  become: true

  pre_tasks:
    - debug:
        msg: "Running devshop/docker/role/play.yml at buildtime..."
      when: ('runtime' not in ansible_run_tags)


    - debug:
        msg: "Running devshop/docker/role/play.yml at runtime..."
      when: ('runtime' in ansible_run_tags)
