---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "30 6 * * 4"

defaults:
  run:
    working-directory: 'geerlingguy.php-versions'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'geerlingguy.php-versions'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Default PHP version (7.4).
          - distro: centos8
            playbook: converge.yml
          - distro: centos7
            playbook: converge.yml
          - distro: ubuntu1804
            playbook: converge.yml
          - distro: debian10
            playbook: converge.yml

          # PHP 8.0.
          - distro: centos8
            playbook: 8.0.yml
          - distro: ubuntu1804
            playbook: 8.0.yml
          - distro: debian10
            playbook: 8.0.yml

          # PHP 7.3.
          - distro: centos8
            playbook: 7.3.yml
          - distro: ubuntu1804
            playbook: 7.3.yml
          - distro: debian10
            playbook: 7.3.yml

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'geerlingguy.php-versions'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
