FROM ubuntu:16.04
RUN apt-get update -qq

# Install Ansible
RUN sed -i 's/101/0/' /usr/sbin/policy-rc.d
RUN apt-get install -y -qq software-properties-common git git curl
RUN apt-add-repository -y ppa:ansible/ansible
RUN apt-get update -qq
RUN apt-get install -y ansible -qq

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
