#!/usr/bin/env php
<?php
/**
 * @file git-remote-monitord
 * Executable file for the git-remote-monitord service.
 *
 * Point your init script or systemd unit file to this file.
 */

global $classLoader;
require 'bootstrap.php';

// The following is modelled on the
use DevShop\Component\GitRemoteMonitor\RemoteMonitorDaemon;

// The daemon needs to know from which file it was executed.
RemoteMonitorDaemon::setFilename(__FILE__);

// The run() method will start the daemon loop.
RemoteMonitorDaemon::getInstance()->run();
