#!/usr/bin/php
<?php
include "bootstrap.php";

use DevShop\Component\GitRemoteMonitor\RemoteMonitorDaemon;

// The daemon needs to know from which file it was executed.
RemoteMonitorDaemon::setFilename(__FILE__);

// The run() method will start the daemon loop.
RemoteMonitorDaemon::getInstance()->run();
