<?php

/**
 * @file devshop_live.module
 *
 * Provides Node Type, UI, and tools for DevShop Live.
 */

include_once('inc/forms.inc');
include_once('inc/nodes.inc');

/**
 * API functions
 */

/**
 * Add new domain to site node
 */
function devshop_live_add_domain($node, $domain) {
  if ($node->type == 'site') {
    if (array_search($domain, $node->aliases) === FALSE) {
      $node->aliases[] = $domain;
      node_save($node);
      return TRUE;
    }
  }

  return FALSE;
}
