---
galaxy_info:
  author: jonpugh
  description: Apache Web Server for DevShop hosting system.
  company: ThinkDrop Inc
  
  license: GPLv2

  min_ansible_version: 2.4

  galaxy_tags:
    - web
    - apache
    - webserver
    - html
    - httpd
    - aegir
    - opendevshop
    - devshop
    - hosting
    - drupal
  
  platforms:
    - name: EL
      versions:
      - 7
      - 6
    - name: Ubuntu
      versions:
      - trusty
      - xenial
      - bionic

dependencies:
  - opendevshop.users
  - geerlingguy.apache
