---
local_bin_path: /usr/local/bin
apache_user: www-data

supervisor_hosting_queued_conf_path: /etc/supervisor/conf.d/hosting-queue-runner.conf

extra_packages:
  - git
  - vim
  - openssl
  - patch
  - postfix
  - cron
  - zip
# @TODO: Trying to solve apache restart problem.
#  - dbus
