---
local_bin_path: /usr/local/sbin
apache_user: apache

# Used to inject date.timezone.
# ip_cli_ini_path: /opt/rh/php55/root/etc/php.ini

extra_packages:
  - git
  - patch
  - postfix
  - sendmail
  - cronie
  - openssl
  - mod_ssl
  - zip
