---
apache_user: apache
apache_control: /usr/sbin/apachectl

apache_vhosts_version: "2.2"
apache_packages:
  - httpd24
  - httpd24-devel
  - mod24_ssl
  - openssh
# Used to inject date.timezone.
# ip_cli_ini_path: /opt/rh/php55/root/etc/php.ini

# @TODO: Make this __extra_packages so people can override them.
extra_packages:
  - git
  - patch
  - postfix
  - sendmail
  - cronie
  - openssl
  - mod_ssl
  - rsync
