<?php

use DigitalOceanV2\Adapter\BuzzAdapter;
use DigitalOceanV2\DigitalOceanV2;

/**
 * Implements hook_hosting_service()
 */
function aegir_digitalocean_hosting_service() {
  $options = variable_get('devshop_cloud_digital_ocean_options', array());
  if (!empty($options)) {
    return array(
      'digital_ocean' => 'provider',
    );
  }
  else {
    return array();
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * Alters devshop cloud settings form to add digital_ocean api keys.
 */
function aegir_digitalocean_form_aegir_cloud_settings_form_alter(&$form, &$form_state) {

  $form['digital_ocean'] = array(
    '#type' => 'fieldset',
    '#title' => t('Digital Ocean'),
    '#weight' => -100,
  );

  $form['digital_ocean']['aegir_cloud_digital_ocean_api_token'] = array(
    '#type' => 'textfield',
    '#title' => t('API token'),
    '#description' => t('Enter your Digital Ocean API token here.'),
    '#default_value' => variable_get('aegir_cloud_digital_ocean_api_token', ''),
  );

}

function aegir_digitalocean_load_api(){
  require_once dirname(__FILE__) . '/digital-ocean-master/vendor/autoload.php';
  require_once dirname(__FILE__) . '/digital-ocean-master/src/DigitalOceanV2.php';
  $api_token = variable_get('aegir_cloud_digital_ocean_api_token', array());

  $adapter = new BuzzAdapter($api_token);
  $digitalocean = new DigitalOceanV2($adapter);
  return $digitalocean;
}

/**
 * Implementation of hook_nodeapi()
 */
function aegir_digitalocean_nodeapi_server_load(&$node) {
  return array('digital_ocean_token' => variable_get('aegir_cloud_digital_ocean_api_token', array()));
}