---

# Supervisor isn't always installed at this point in the play, so allow errors.
- name: "User ID Change: Stop supervisord"
  supervisorctl:
    name: hosting-queue-runner
    state: stopped
  ignore_errors: true

- name: "User ID Change: Find all user processes"
  shell: "ps -ef | grep -v grep | grep -w {{ aegir_user_name }} | awk '{print $2}'"
  register: running_processes

- name: Aegir User Processes
  debug:
    var: running_processes

- name: "User ID Change: Kill all user processes"
  command: "kill {{ item }}"
  ignore_errors: true
  with_items: "{{ running_processes.stdout_lines }}"

- name: "User ID Change: Wait for all processes to end"
  wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ running_processes.stdout_lines }}"
  ignore_errors: true
  register: killed_processes

- name: "User ID Change: Force stop stuck processes"
  command: "kill -9 {{ item }}"
  with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"
