# New.
---
version: '3'
services:
  devshop.server:
    volumes:
      - ../:/usr/share/devshop
      - $HOME/.ssh:/var/aegir/.ssh

    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 idekey=PHPSTORM"