# DevShop Docker Images
# Build Tool
#
# This docker-compose file is only for building containers.
#
---
version: '2.2'
services:

  # DevShop Base Image
  # FROM ubuntu or centos
  # The OS and SystemD changes to allow it to run in containers.
  base:
    image: "devshop/base:${OS:-latest}"
    build:
      context: ".."
      dockerfile: "docker/base/Dockerfile.${OS:-ubuntu1804}"

  # DevShop Ansible Image
  # devshop/base + ansible + python
  ansible:
    image: "devshop/ansible:${OS:-latest}"
    depends_on:
      - base
    build:
      context: ".."
      dockerfile: "docker/ansible/Dockerfile.${OS:-ubuntu1804}"

  # DevShop Core Image
  # devshop/ansible + php + composer + devshop/cli
  core:
    image: "devshop/core:${OS:-latest}"
    depends_on:
      - ansible
    build:
      context: ".."
      dockerfile: "docker/core/Dockerfile.${OS:-ubuntu1804}"

  # DevShop Role Image
  # devshop/core + tools to use any Ansible role at runtime.
  role:
    image: "devshop/role:${OS:-latest}"
    depends_on:
      - core
    build:
      context: ".."
      dockerfile: "docker/role/Dockerfile.${OS:-ubuntu1804}"
