#
# DevShop Remote Server container
#
FROM devshop/server:latest

LABEL maintainer="Jon Pugh"

RUN echo "Building container from Dockerfile.remote, from $DEVSHOP_CONTAINER_FROM ..."
RUN apt-get install openssh-server -y

#ENV DEVSHOP_DOCKER_COMMAND_RUN ""

ENTRYPOINT /usr/share/devshop/docker/bin/docker-systemd-entrypoint
#CMD ""

RUN devshop-logo 'DevShop Remote Server container build finished.'
