# New.
---
version: '3'
services:
  devshop.server:
    image: ${DEVSHOP_DOCKER_IMAGE:-devshop/server:latest}
    build:
      context: ".."
      dockerfile: "docker/Dockerfile.${OS:-ubuntu1804}"
      args:
        # see .env files for defaults.
        - DEVSHOP_CONTAINER_FROM
        - DEVSHOP_DOCKER_COMMAND_BUILD_ARG
        - ANSIBLE_PLAYBOOK_COMMAND_OPTIONS_ARG
        - ANSIBLE_EXTRA_VARS
    hostname: devshop.local.computer
    ports:
      - "80:80"
      - "2222:22"
      - "33066:3306"
    privileged: true
    entrypoint: /usr/share/devshop/docker/bin/docker-systemd-entrypoint
    volumes:
      # - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # Attempting tip from https://github.com/geerlingguy/docker-ubuntu2004-ansible/issues/18#issuecomment-1152157965
      - /sys/fs/cgroup:/sys/fs/cgroup

    environment:
      - ANSIBLE_EXTRA_VARS
      - ANSIBLE_VERBOSITY
      - ANSIBLE_PLAYBOOK_COMMAND_OPTIONS
      - ANSIBLE_PLAYBOOK=/usr/share/devshop/roles/devshop.server/play.yml
      - DOCKER_COMMAND_POST
      - GITHUB_HEAD_REF
      - DEVSHOP_TESTS_ARTIFACTS_PATH
      # Setting this ensures the docker containers have this value, regardless if the container is an older image.
      - DEVSHOP_ANSIBLE_GROUP_NAME=devshop_server
