version: "2.1"
services:
  devshop:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: devshop/server
    container_name: devshop
    restart: unless-stopped
    hostname: devshop.local.computer
    
    volumes:
      - ../:/usr/share/devshop
      - ../aegir-home:/var/aegir
      - /var/lib/mysql

    environment:
      - PUID=${PGUID:-1000}
      - PGID=${PGUID:-1000}
      - TZ=America/New_York

    ports:
      - 80:80
      - 443:443
