# New.
---
version: '3'
services:
  devshop.server:
    image: ${DEVSHOP_DOCKER_IMAGE:-devshop/server:php8.1}
    build:
      context: ".."
      dockerfile: "docker/Dockerfile"
      args:
        # see .env files for defaults.
        # - DEVSHOP_CONTAINER_FROM
        - DEVSHOP_DOCKER_COMMAND_BUILD_ARG
        - ANSIBLE_EXTRA_VARS_ARG
# Not if we are using build args.
#        - ANSIBLE_TAGS_ARG
        - ANSIBLE_PLAYBOOK_COMMAND_OPTIONS_ARG
    hostname: devshop.local.computer
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
      - "33066:3306"
    privileged: true
#    entrypoint: /usr/share/devshop/docker/bin/docker-systemd-entrypoint
    volumes:
      - /var/lib/mysql
      - /var/aegir

#    volumes:
      # - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # Attempting tip from https://github.com/geerlingguy/docker-ubuntu2004-ansible/issues/18#issuecomment-1152157965
      # - /sys/fs/cgroup:/sys/fs/cgroup:rw

    environment:
      - ANSIBLE_EXTRA_VARS
      # This is set in Dockerfile.
      # - ANSIBLE_TAGS=runtime
      - ANSIBLE_VERBOSITY
      - ANSIBLE_PLAYBOOK_COMMAND_OPTIONS
      - ANSIBLE_PLAYBOOK=/usr/share/devshop/roles/devshop.server/play.yml
      - DEVSHOP_DOCKER_COMMAND_RUN
      - DOCKER_COMMAND_POST
      - GITHUB_HEAD_REF
      - DEVSHOP_TESTS_ARTIFACTS_PATH
      # Setting this ensures the docker containers have this value, regardless if the container is an older image.
      - DEVSHOP_ANSIBLE_GROUP_NAME=devshop_server
