# New.
---
version: '3'
services:
  devshop.server:
    # Use the pre-built images for speed.
    image: ${DEVSHOP_DOCKER_IMAGE:-devshop/server:php8.0}
    command: devshop-ansible-playbook
    volumes:
      - ../:/usr/share/devshop
      - ../aegir-home:/var/aegir
      - $HOME/.ssh:/var/aegir/.ssh
