# New.
---
version: '3'
services:
  # The container, ie just a shell.
  container:
    image: "devshop/container"
    build:
      context: ".."
      dockerfile: "docker/Dockerfile.${OS:-ubuntu1804}"
    hostname: devshop.local.computer
    ports:
      - "80:80"
      - "2222:22"
      - "33066:3306"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/mysql

    environment:
      - ANSIBLE_EXTRA_VARS
      - ANSIBLE_VERBOSITY
      - ANSIBLE_PLAYBOOK_COMMAND_OPTIONS
