# New.
---
version: '3'
services:
  devshop.server:
    image: "devshop/server"
    build:
      context: ".."
      dockerfile: "docker/Dockerfile.${OS:-ubuntu1804}"
    hostname: devshop.local.computer
    ports:
      - "80:80"
      - "2222:22"
      - "33066:3306"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

    environment:
      - ANSIBLE_EXTRA_VARS
      - ANSIBLE_VERBOSITY
      - ANSIBLE_PLAYBOOK_COMMAND_OPTIONS
      - ANSIBLE_PLAYBOOK=/usr/share/devshop/roles/devshop.server/play.yml
      - DOCKER_COMMAND_POST
      - GITHUB_HEAD_REF
      - DEVSHOP_TESTS_ARTIFACTS_PATH
      # Setting this ensures the docker containers have this value, regardless if the container is an older image.
      - DEVSHOP_ANSIBLE_GROUP_NAME=devshop_server
