# New.
---
version: '3'
services:
  devshop.server:
    image: ${DEVSHOP_DOCKER_IMAGE:-devshop/server:php8.1}
# Builds Break. We must upgrade to ubuntu 20
#    build:
#      context: ".."
#      dockerfile: "docker/Dockerfile.${OS:-ubuntu2004}"
#      args:
#        # see .env files for defaults.
#        - DEVSHOP_CONTAINER_FROM
#        - DEVSHOP_DOCKER_COMMAND_BUILD_ARG
#        - ANSIBLE_EXTRA_VARS_ARG
#        - ANSIBLE_TAGS_ARG
#        - ANSIBLE_PLAYBOOK_COMMAND_OPTIONS_ARG
    hostname: devshop.local.computer
    ports:
      - "80:80"
      - "443:443"
#      - "2222:22"
      - "33066:3306"
    privileged: true
    entrypoint: /usr/share/devshop/docker/bin/docker-systemd-entrypoint
    volumes:
      - /var/lib/mysql
      - /var/aegir
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

#    volumes:
      # - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # Attempting tip from https://github.com/geerlingguy/docker-ubuntu2004-ansible/issues/18#issuecomment-1152157965
      # - /sys/fs/cgroup:/sys/fs/cgroup:rw

    environment:
      - ANSIBLE_EXTRA_VARS
      - ANSIBLE_TAGS=runtime
      - ANSIBLE_VERBOSITY
      - ANSIBLE_PLAYBOOK_COMMAND_OPTIONS
      - ANSIBLE_PLAYBOOK=/usr/share/devshop/roles/devshop.server/play.yml
      - DEVSHOP_DOCKER_COMMAND_RUN
      - DOCKER_COMMAND_POST
      - GITHUB_HEAD_REF
      - DEVSHOP_TESTS_ARTIFACTS_PATH
      # Setting this ensures the docker containers have this value, regardless if the container is an older image.
      - DEVSHOP_ANSIBLE_GROUP_NAME=devshop_server

  devshop.remote:
    image: devshop/remote:latest
    build:
      context: ".."
      dockerfile: "docker/Dockerfile.remote"
    hostname: remote.local.computer
    ports:
      - "8080:80"
      - "4433:443"
      - "2222:22"
#      - "33066:3306"
    privileged: true
    volumes:
      - /var/lib/mysql
      - ../:/usr/share/devshop
    command:
      - "devshop-ansible-playbook"
    entrypoint: /usr/share/devshop/docker/bin/docker-systemd-entrypoint
    environment:
      DEVSHOP_DOCKER_COMMAND_RUN: "echo 'Welcome to devshop.remote container.'"
      DEVSHOP_ANSIBLE_GROUP_NAME: devshop_remote
      ANSIBLE_EXTRA_VARS:
      ANSIBLE_PLAYBOOK_COMMAND_OPTIONS:

