<?php
/*
 * @file devshop_projects.module: a module in the DevShop module group 
 * which enables the user to create proects and group sites/platforms
 * into project groups.
 */

/**
 * Implementation of hook_perm()
 */
function devshop_projects_perm() {
  return array(
    'view projects',
  );
}

/**
 * Implementation of hook_menu()
 */
function devshop_projects_menu() {

  $items['hosting/projects'] = array(
    'title' => 'Projects',
    'description' => 'Display a list of all projects',
    'page callback' => 'devshop_projects_projects_view',
    'access arguments' => array('view projects'),
  );

  return ($items);
}

/*
 * Callback that is invoked when the user points the brower to
 * hosting/projects. It displays a nice tabulated list of projects
 * and cool thing you can do with them.
 */

function devshop_projects_projects_view() {
  if ($list = drupal_get_form('devshop_projects_projects_list_form')) {
    return $list;
  }
  $create_project_link = l(t('Create a site now?'), 'node/add/project');
  return t("No projects have been created yet. !link", array(
    '!link' => $create_project_link));
}

/**
 * Create a form for building a list of projects.
 */
function devshop_projects_projects_list_form($form_state, $filter_by = NULL, $filter_value = NULL) {
 
  return array();
} 
