<?php

/**
 * Implements hook_menu()
 */
function devshop_softlayer_menu(){
  $items = array();
  $items['admin/devshop/cloud_softlayer'] = array(
    'title' => 'SoftLayer',
    'description' => 'Retrieve options from softlayer.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devshop_softlayer_options_form'),
    'access arguments' => array('administer devshop cloud'),
    'file' => 'options.php',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}
/**
 * Implements hook_hosting_service()
 */
function devshop_softlayer_hosting_service() {
  return array(
    'softlayer' => 'provider',
  );
}

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * Alters devshop cloud settings form to add softlayer api keys.
 */
function devshop_softlayer_form_devshop_cloud_settings_form_alter(&$form, &$form_state) {

  $form['softlayer'] = array(
    '#type' => 'fieldset',
    '#title' => t('SoftLayer'),
    '#weight' => -100,
  );

  $form['softlayer']['devshop_cloud_softlayer_api_username'] = array(
    '#type' => 'textfield',
    '#title' => t('API Username'),
    '#description' => t('Enter your softlayer username here.'),
    '#default_value' => variable_get('devshop_cloud_softlayer_api_username', ''),
  );

  $url = 'https://control.softlayer.com/account/users';
  $form['softlayer']['devshop_cloud_softlayer_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('API Key'),
    '#description' => t('Enter your SoftLayer API key here.  Get your API key at !link', array(
      '!link' => l($url, $url),
    )),
    '#default_value' => variable_get('devshop_cloud_softlayer_api_key', ''),
  );


}