<?php
/**
 * @file
 * The hosting server data example.
 */

/**
 * Implements hook_form_alter().
 */
function ansible_variables_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'server_node_form') {

    $form['ansible_variables'] = array(
      '#type' => 'fieldset',
      '#title' => t('Server data example'),
      '#description' => t('Example implementation of saving data into the server context.'),
    );

    $form['ansible_variables']['ansible_variables'] = array(
      '#type' => 'textfield',
      '#title' => t('Server data'),
      '#default_value' => isset($form['#node']->ansible_variables) ? $form['#node']->ansible_variables : '',
      '#weight' => 0,
    );
    return $form;
  }
}

/**
 * Implements hook_node_insert().
 */
function ansible_variables_node_insert($node) {
  if ($node->type == 'server' && !empty($node->ansible_variables)) {
    $id = db_insert('ansible_variables')->fields(array(
      'vid' => $node->vid,
      'nid' => $node->nid,
      'ansible_variables' => $node->ansible_variables,
    ))
    ->execute();
  }
}

/**
 * Implements hook_node_update().
 */
function ansible_variables_node_update($node) {
  if (FALSE === db_query("SELECT ansible_variables FROM {ansible_variables} WHERE vid = :vid", array(':vid' => $node->vid))->fetchField()) {
    ansible_variables_node_insert($node);
  }
  else {
    db_update('ansible_variables')
      ->fields(array(
        'ansible_variables' => $node->ansible_variables,
      ))
      ->condition('vid', $node->vid)
      ->execute();
  }
}

/**
 * Implements hook_node_load().
 */
function ansible_variables_node_load($nodes, $types) {
  foreach ($nodes as $nid => &$node) {
    if ($node->type == 'server') {
      // array instead
      $nodes[$nid]->ansible_variables = db_query("SELECT ansible_variables FROM {ansible_variables} WHERE vid = :vid", array(':vid' => $node->vid))->fetchField();;
    }
  }
}

/**
 * Implements hook_node_delete().
 */
function ansible_variables_node_delete($node) {
  db_delete('ansible_variables')
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * Implements hook_revision_revision().
 */
function ansible_variables_node_revision_delete($node) {
  db_delete('ansible_variables')
    ->condition('vid', $node->vid)
    ->execute();
}
