#!/usr/bin/env bash

# Thank you composer for figuring this out!
selfArg="$BASH_SOURCE"
if [ -z "$selfArg" ]; then
    selfArg="$0"
fi

self=$(realpath $selfArg 2> /dev/null)
if [ -z "$self" ]; then
    self="$selfArg"
fi

dir=$(cd "${self%[/\\]*}" > /dev/null; cd '../scripts' && pwd)

PATH="$dir:$PATH"
REF=$(cd $dir && branch-or-tag)
VERSION=${REF:-=$(cat $dir/../.git/HEAD)}

echo '
    ____              ____  _
   |  _ \  _____   __/ ___|| |__   ___  _ __
   | | | |/ _ \ \ / /\___ \|  _ \ / _ \|  _ \
   | |_| |  __/\ V /  ___) | | | | (_) | |_) |
   |____/ \___| \_/  |____/|_| |_|\___/| .__/
            http://getdevshop.com      |_|'
echo " Version $VERSION    "
echo " Path $DEVSHOP_PATH    "

if [ -z "$1" ]; then exit; fi

devshop-line
echo " $1 "
devshop-line

