#!/usr/bin/env sh

# Support bash to support `source` with fallback on $0 if this does not run with bash
# https://stackoverflow.com/a/35006505/6512
selfArg="$BASH_SOURCE"
if [ -z "$selfArg" ]; then
    selfArg="$0"
fi

self=$(realpath $selfArg 2> /dev/null)
if [ -z "$self" ]; then
    self="$selfArg"
fi

usage() {
  echo -n "${scriptName} [OPTION]... [FILE]...

Returns true if local working copy is behind the git remote.
"
}

git fetch
BEHIND=$(git rev-list HEAD..FETCH_HEAD --count)

if  [ "$BEHIND" -gt "0" ]; then
  exit 0
else
  exit 1
fi
