#!/usr/bin/env bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PATH="$DIR:$PATH"

# This script just calls the "drush" executable in this folder, with the drush command "hosting-queued" on the @hostmaster site.
# See hosting_queued.drush.inc

# Set timeout to 5 minutes
export TIMEOUT=300
wait-site @hostmaster

devshop-log "Clearing drush caches ..."
drush @hostmaster cc drush

devshop-log "Running drush @hostmaster hosting-queued ..."
drush @hostmaster hosting-queued
