<?php
/**
 * @file devshop_pull.module
 *
 * Provides a Hosting Queue and a URL callback for remote services to ping, in
 * order to trigger a Pull Code task.
 *
 * Used to keep a dev server up to date with the commits of projects.
 *
 */

define('DEVSHOP_PULL_DISABLED', 0);
define('DEVSHOP_PULL_QUEUE', 1);
define('DEVSHOP_PULL_CALLBACK', 2);

define('DEVSHOP_PULL_STATUS_OK', 1);
define('DEVSHOP_PULL_STATUS_ACCESS_DENIED', 2);
define('DEVSHOP_PULL_STATUS_INVALID_CODE', 3);

// These are github's Webhook callback IPs.
// This list grows occaisonally, update it as needed.
define('DEVSHOP_PULL_DEFAULT_ALLOWED_IPS',"
204.232.175.64/27
192.30.252.0/22
");

// The base URL to use for the Post Commit callback.
define('DEVSHOP_PULL_CALLBACK_URL', 'webhook');

/**
 * Implements hook_perm()
 */
function devshop_pull_perm() {
  return array(
    'configure devshop pull',
  );
}

/**
 * Implements hook_menu()
 */
function devshop_pull_menu() {
  $items['admin/hosting/devshop/pull'] = array(
    'title' => 'Pull',
    'description' => 'Configure Pull Code URL callback ',
    'page callback' => 'devshop_pull_settings_page',
    'access arguments' => array('administer hosting settings'),
    'file' => 'devshop_pull.settings.inc',
    'tab_parent' => 'admin/hosting/devshop',
    'type' => MENU_LOCAL_TASK,
  );
  $items[DEVSHOP_PULL_CALLBACK_URL] = array(
    'page callback' => 'devshop_pull_callback',
    'access callback' => TRUE,
    'file' => 'devshop_pull.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}
