<?php

/**
 * @file devshop_projects.module
 * a module in the DevShop module group which enables the user to create 
 * proects and group sites/platforms into project groups.
 */

/**
 * Implementation of hook_perm()
 */
function devshop_projects_testing_perm() {
  return array(
    'run project tests',
  );
}

/**
 * Implements hook_form_alter().
 */
function devshop_projects_testing_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'project_node_form') {
    $form['tests_to_run'] = array(
      '#type' => 'textarea',
      '#title' => t('Tests To Run'),
      '#default_value' => $form['#node']->tests_to_run,
      '#rows' => 6,
      '#description' => t('Enter the names of the simpletests to trigger when "Run Tests" task is started, one per line.  See the !link for examples.', array('!link' => l(t('Drupal API'), 'http://api.drupal.org/api/drupal/modules%21simpletest%21drupal_web_test_case.php/class/DrupalWebTestCase/7'))),
      '#weight' => 20,
    );
  }
}

/**
 * Implements hook_nodeapi()
 */
function devshop_projects_testing_nodeapi(&$node, $op, $a3 = null) {

  if ($node->type != 'project' || $a3 != null) {
    return;
  }

  switch ($op) {
  case 'load':
    $data = db_fetch_array(db_query("SELECT tests_to_run " .
				     "FROM {hosting_devshop_project_testing} ".
				     "WHERE project_nid = %d", $node->nid));
    return $data;

  case 'view':

    break;


  case 'insert':
  case 'update':
    db_query("DELETE FROM {hosting_devshop_project_testing} " .
	     "WHERE project_nid = %d", $node->nid);

    db_query("INSERT INTO {hosting_devshop_project_testing} " .
	     "(project_nid, tests_to_run) " .
	     "VALUES(%d, '%s')", $node->nid, $node->tests_to_run);
    break;

  case 'delete':
    db_query("DELETE FROM {hosting_devshop_project_testing} " .
	     "WHERE project_nid = %d", $node->nid);
    break;

  default:
    break;
  }

}

/**
 * Implementation of hook_hosting_tasks()
 *
 */
function devshop_projects_testing_hosting_tasks() {
  $tasks = array();

  $tasks['site']['devshop-test'] = array(
    'title' => t('Run Tests'),
    'description' => t('Run a group of previousely defined SimpleTest tests.'),
    'dialog' => TRUE,
    'task_permitted' => TRUE,
    'access callback' => 'devshop_projects_testing_access',
  );

  return $tasks;
}

/*
 * Task access callback hook
 *
 * Returne TRUE is this is a site node and qualifies to run tests.
 * To qualify, it much be part of a devshop project group and must
 * be either the 'test' site or one of the branch sites.
 */
function devshop_projects_testing_access($node, $type) {

  if ($node->type != 'site' || !$node->project_nid) {
    return FALSE;
  }

  $query = db_query("SELECT * FROM {hosting_devshop_project_object} " .
		    "WHERE object_nid = %d", $node->nid);

  if (!($obj = db_fetch_object($query))) {
    // This should not happen, but let's check for it anyway
    return FALSE;
  }

  if ($obj->environment == 'live' || $obj->environment == 'dev') {
    return FALSE;
  }

  // Everything else is OK
  return TRUE;
}

/**
 * Implementation of hook_hosting_task_TASK_TYPE_form().
 *
 */
function hosting_task_devshop_test_form($node) {

  if ($node->project_nid) {
    $project_node = node_load($node->project_nid);
    $tests = $project_node->tests_to_run;
  }
  else {
    $tests = "";
  }

  $form['tests_to_run'] = array(
    '#type' => 'textarea',
    '#title' => t('Tests To Run'),
    '#default_value' => $tests,
    '#rows' => 6,
    '#description' => t('Enter the names of the simpletests to run when this project receives a commit, one per line.'),
    );

  $form['sync'] = array(
    '#type' => 'checkbox',
    '#title' => t("Sync from Live before testing?"),
    '#default_value' => FALSE,
  );

  return $form;
}

/**
 * Implementation of hook_hosting_task_TASK_TYPE_form_validate().
 *
 */
function hosting_task_devshop_test_form_validate($form, &$form_state) {

  $tests = $form_state['values']['parameters']['tests_to_run'];
  $t = trim(str_replace("\n", "", $tests));

  if (empty($tests) || empty($t) || $tests == "" || $t == ""){
    form_set_error('tests_to_run', t('You must include at least one test.'));
  }


}

