<?php
/**
 * @file devshop_projects.module
 * a module in the DevShop module group which enables the user to create proects and group
 * sites/platforms into project groups.
 */

/**
 * Implementation of hook_hosting_tasks()
 */
function devshop_projects_hosting_tasks() {
  $tasks = array();
  $tasks['project']['devshop-create'] = array(
    'title' => t('Create Project'),
    'description' => t('Clones the repo, and creates the platforms.'),
  );
  return $tasks;
}

/**
 * Implements hook_hosting_CONTEXTTYPE_context_options()
 */
function devshop_projects_hosting_project_context_options(&$task) {
  $task->context_options['server'] = '@server_master';
  $task->context_options['project_name'] = $task->ref->title;
  $task->context_options['code_path'] = trim($task->ref->code_path, " ");
  if ($task->ref->git_url) {
    $task->context_options['git_url'] = $task->ref->git_url;
  }
}

/**
 * Implementation of hook_perm()
 */
function devshop_projects_perm() {
  return array(
    'view projects',
  );
}

/**
 * Implementation of hook_node_info().
 */
function devshop_projects_node_info() {
  #configuration
  $types["project"] =  array(
    "type" => 'devshop_project', 
    "name" => 'DevShop Project',
    "module" => 'devshop_projects',
    "has_title" => TRUE, 
    "title_label" => t('Project Codename'),
    "description" => t('Create a project'),
    "has_body" => 0, 
    "body_label" => '', 
    "min_word_count" => 0
    );

  return $types;
}

/**
 * Implementation of hook_menu()
 */
function devshop_projects_menu() {

  $items['hosting/projects'] = array(
    'title' => 'Projects',
    'description' => 'Display a list of all projects',
    'page callback' => 'devshop_projects_projects_view',
    'access arguments' => array('view projects'),
  );

  $items['hosting/projects/detail/%'] = array(
    'title' => 'Projects Details',
    'description' => 'Display details of a projects',
    'page callback' => 'devshop_projects_project_detail',
    'access arguments' => array('view projects'),
  );

  return ($items);
}

/*
 * Callback that is invoked when the user points the brower to
 * hosting/projects. It displays a nice tabulated list of projects
 * and cool thing you can do with them.
 */

function devshop_projects_projects_view() {

  $header = array('Projects', 'Sites');

  $r = db_query("SELECT * FROM {hosting_devshop_project}");
  $rows = array();

  while(($proj = db_fetch_object($r))) {
    $node = node_load($proj->nid);
    $row = array();
    $row[] = $node->title;
    $row[] = db_result(db_query("SELECT COUNT(*) " .
				"FROM {hosting_devshop_project_sites} " .
				 "WHERE nid = %d", $node->nid));
    $rows[] = $row;
  }

  $output = theme('table', $header, $rows, array('class' => 'hosting-table'));
  $output .= l(t('Create a new project?'), 'node/add/devshop-project');
  return $output;
}

/**
 * Create a form for building a list of projects.
 */
function devshop_projects_projects_list_form($form_state, $filter_by = NULL, $filter_value = NULL) {
 
  return array();
} 

/**
 * hook_nodeapi()
 */
function devshop_projects_nodeapi(&$node, $op, $a3 = null) {

  $etype = array('dev' => 'Dev',
  	   	 'test' => 'Test',
		 'live' => 'Live');

  if ($node->type == 'site') {
    switch ($op) {
      case 'view':
        if (!$a3) { //!teaser
          $node->content['info']['environment'] = array(
	    '#type' => 'item',
    	    '#title' => t('Environment Type'),
            '#value' => t($etype[$node->environment]),
    	    '#description' => t('')
  	    );

        }
        break;

    case 'load':
      if (!empty($url)){
        $node->git_url = $url;
      }
      break;

    case 'insert':
    case 'update':
/*
      db_query("DELETE FROM {hosting_platform_git} " .
      	       "WHERE nid = %d", $node->nid);
      db_query("INSERT INTO {hosting_platform_git} " .
               "(nid, git_url, cloned) " .
               "VALUES (%d, '%s', 0)", 
	       $node->nid, $node->git_url);
*/
      break;
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function devshop_projects_form_alter(&$form, &$form_state, $form_id){
  if ($form_id == 'project_node_form'){
    unset($form['menu']);
    unset($form['revision_information']);
    unset($form['author']);
    unset($form['options']);
  }
}

/**
 * Implementation of hook_form().
 */
function devshop_projects_form(&$node) {

  $form['git_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Git URL'),
    '#required' => TRUE,
    '#description' => t(''),
    '#required' => TRUE,
    '#size' => 40,
    '#default_value' => $node->git_url,
    '#maxlength' => 255,
    '#weight' => 1,
  );
  
  if(!$node->nid) {
    $form['title'] = array(
      '#type' => 'textfield',
       '#title' => t('Project Code Name'),
       '#required' => TRUE,
       '#description' => t('Choose a unique name for your project.'),
       '#size' => 40,
       '#default_value' => $node->title,
       '#maxlength' => 255,
       );
  }
  else {
    $form['title'] = array(
      '#type' => 'item',
      '#title' => t('Project Code Name'),
      '#value' => $node->title
      );
  }


  if(!$node->nid) {
    $form['code_path'] = array(
      '#type' => 'textfield',
      '#title' => t('Code path'),
      '#description' => t('The absolute path on the filesystem that will be used to create the platform in the directory specified above.'),
      '#required' => TRUE,
      '#size' => 40,
      '#default_value' => $node->code_path,
      '#maxlength' => 255,
      '#weight' => 2,
      );
  }
  else {
    $form['code_path'] = array(
      '#type' => 'item',
      '#title' => t('Code path'),
      '#value' => $node->code_path
      );
  }
  
  //@TODO: Remove.  I think that instead, we should let the script create the platforms.
  //  We have to pause at that point anyway, so the user can choose the available install profiles for their three sites.
  //  Lets let provision-devshop-create import all three platforms and verify, then let the users MIGRATE their existing
  //  sites ONTO the new platforms, IF they wish.  In my opinion, migration of the old sites to our automatically built
  //  platforms is a better way to go.
  //
//
//  $sites = array(0 => 'None');
//  $r = db_query("SELECT n.nid, n.title FROM {node} AS n " .
//       		"LEFT JOIN {hosting_site} AS h ON n.nid = h.nid " .
//		"WHERE n.type = 'site' AND h.status = 1 " .
//		"ORDER BY n.title ASC");
//
//  while($sa = db_fetch_object($r)) {
//    $sites[$sa->nid] = $sa->title;
//  }
//
//  $form['dev_site'] = array(
//    '#type' => 'select',
//    '#title' => t('DEV Site'),
//    '#options' => $sites,
//    '#description' => t('Select site that is going to be your development site.'),
//    '#default_value' => $node->dev_site,
//    '#weight' => 20,
//  );
//
//  $form['test_site'] = array(
//    '#type' => 'select',
//    '#title' => t('TEST Site'),
//    '#options' => $sites,
//    '#description' => t('Select site that is going to be your test site.'),
//    '#default_value' => $node->test_site,
//    '#weight' => 21,
//  );
//
//  $form['live_site'] = array(
//    '#type' => 'select',
//    '#title' => t('LIVE Site'),
//    '#options' => $sites,
//    '#description' => t('Select site that is going to be your live site.'),
//    '#default_value' => $node->live_site,
//    '#weight' => 22,
//  );

  return $form;
}
//
///**
// * Insert the sites into the sites table
// */
//function _devshop_projects_insert_sites($node) {
//
//  foreach(array('dev_site' => 'dev', 
//                'test_site' => 'test', 
//                'live_site' => 'live') as $k => $v) {
//    if($node->$k) {
//      $snode = node_load($node->$k);
//      db_query("INSERT INTO {hosting_devshop_project_sites} " .
//               "(nid, site_nid, platform_nid, env_type) " .
//	       "VALUES (%d, %d, %d, '%s')",
//	       $node->nid, $node->$k, $snode->platform, $v);
//    }
//  }
//}

/**
 * Implementation of hook_insert().
 */
function devshop_projects_insert($node) {

  db_query("INSERT INTO {hosting_devshop_project} (nid, git_url, code_path) ".
  	   "VALUES (%d, '%s', '%s')",
	   $node->nid, $node->git_url, hosting_path_normalize($node->code_path));
//  _devshop_projects_insert_sites($node);

  // Save hosting context
  if ((!$node->old_vid)) {
    hosting_context_register($node->nid, ($node->hosting_name) ? $node->hosting_name : $node->title);
  }
  
  // Create hostmaster task
  $args = array();
  $args['git-url'] = $node->git_url;
  $args['path'] = $node->code_path;
  hosting_add_task($node->nid, 'devshop-create', $args);
}

/**
 * Implementation of hook_update().
 *
 * As an existing node is being updated in the database, we need to do our own
 * database updates.
 */
function devshop_projects_update($node) {
  // if this is a new node or we're adding a new revision,
  if (!empty($node->revision)) {
    hosting_devshop_project_insert($node);
  }
  else {
    db_query("UPDATE {hosting_devshop_project} " .
             "SET git_url = '%s', code_path = '%s' WHERE nid=%d",
              $node->git_url, hosting_path_normalize($node->code_path));
    db_query('DELETE FROM {hosting_devshop_project_sites} WHERE nid = %d', $node->nid);
    _devshop_projects_insert_sites($node);
  }
}

/**
 * Implementation of hook_delete().
 */
function devshop_projects_delete($node) {
  db_query('DELETE FROM {hosting_devshop_project} WHERE nid = %d', $node->nid);
  db_query('DELETE FROM {hosting_devshop_project_sites} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_validate().
 */
function devshop_projects_validate($node, &$form) {
  // No validation if op == Delete
  if ($node->op == t('Delete')) {
    return;
  }

  // Full validation on when a creating a new node
  $add = (arg(1) == 'add' ? TRUE : FALSE);

  // Title (project code) must not have any spaces
  if(strpos($node->title, ' ') != FALSE) {
    form_set_error('title', t('Project code name must not contain any white spaces.'));
  }

  // The project code name must not be in the hosting_context table
  if ($result = db_fetch_object(db_query("SELECT name FROM {hosting_context} WHERE name = '%s'", $node->title))) {
    form_set_error('title', t('Project code name existing in hosting context table.'));
  }

  // The project code name must be unique
  if ($result = db_fetch_object(db_query("SELECT title FROM {node} WHERE title = '%s' AND type = 'devshop_project' AND	nid <> %d", $node->title, $node->nid))) {
    form_set_error('title', t('Project code name is already is use by another project'));
  }

  // Make sure the path is unique. 
  $cp = hosting_path_normalize($node->code_path);
  if ($add && $result = db_fetch_object(db_query("SELECT code_path FROM {hosting_devshop_project} WHERE code_path = '%s' AND nid <> %d", $cp, $node->nid))) {
    form_set_error('code_path', t('Code path is already in use by another project'));
  }

  // Directory must not exist
  if ($add && file_exists($cp)) {
    form_set_error('code_path', t('Code path directory already exists.'));
  }

  // Sites may not be used in more than one environement
  if($node->dev_site != 0 && $node->dev_site == $node->test_site) {
    form_set_error('dev_site', t('Site used more than once.'));
    form_set_error('test_site', t('Site used more than once.'));
  }

  if($node->dev_site != 0 && $node->dev_site == $node->live_site) {
    form_set_error('dev_site', t('Site used more than once.'));
    form_set_error('live_site', t('Site used more than once.'));
  }

  if($node->test_site != 0 && $node->test_site == $node->live_site) {
    form_set_error('test_site', t('Site used more than once.'));
    form_set_error('live_site', t('Site used more than once.'));
  }
}

/**
 * Implementation of hook_load().
 *
 * @param node
 *    Node object
 */
function devshop_projects_load($node) {
  $additions = db_fetch_array(db_query('SELECT git_url, code_path ' .
                                        'FROM {hosting_devshop_project} ' .
                                        'WHERE nid = %d', $node->nid));
  $hosting_name = db_fetch_array(db_query("SELECT name AS hosting_name FROM {hosting_context} WHERE nid = %d", $node->nid));
  if (is_array($hosting_name) && is_array($additions)) {
    $hosting_name['hosting_name'] = 'project_' . $hosting_name['hosting_name'];
    $additions += $hosting_name;
  }
  $env =   array('dev'  => 'dev_site', 
                 'test' => 'test_site', 
                 'live' => 'live_site');

  $r = db_query("SELECT * FROM {hosting_devshop_project_sites} " .
                "WHERE nid = %d", $node->nid);

  while(($e = db_fetch_object($r))) {
    if(!empty($env[$e->env_type])) {
      $additions[$env[$e->env_type]] = $e->site_nid;
    }
  }
  return $additions;
}

/**
 * Implementation of hook_view().
 */
function devshop_projects_view($node, $teaser = FALSE, $page = FALSE) {
  modalframe_parent_js();

  $node->content['info'] = array(
    '#prefix' => '<div id="hosting-platform-info">',
    '#suffix' => '</div>'
  );

  $node->content['info']['git_url'] = array(
    '#type' => 'item',
    '#title' => t('Git URL'),
    '#value' => $node->git_url,
    '#weight' => -10
  );

  $node->content['info']['code_path'] = array(
    '#type' => 'item',
    '#title' => t('Code path'),
    '#value' => filter_xss($node->code_path),
    '#weight' => -8
  );

  $header = array('Environement', 'Site');
  $rows = array();
  foreach(array('dev_site' => 'DEV Site', 
                'test_site' => 'TEST Site', 
                'live_site' => 'LIVE Site') as $k => $v) {

    $row = array($v, $node->$k ? node_load($node->$k)->title :
       	 	      "Not assigned yet");
    $rows[] = $row;
  }

  $table = theme('table', $header, $rows);

  $node->content['info']['sites'] = array(
    '#type' => 'item',
    '#title' => t('Project Members'),
    '#value' => $table,
    '#weight' => -7
  );
 
  return $node;
}

/**
 * Hide the delete button on project nodes.
 */
function hosting_devshop_projects_form_alter(&$form, &$form_state, $form_id) {
  // Remove delete button from the edit form
  if ($form_id == 'devshop_project_node_form') {
    $form['buttons']['delete']['#type'] = 'hidden'; 
  }
}

function devshop_projects_project_detail() {

  $nid = arg(3); // ok, I'm cheating
  if(!($node = node_load($nid)) || $node->type != 'devshop_project') {
    return t('Project not found!');
  }

  return "hello";
}
