<?php

namespace ProvisionOps\Tools;

use Psr\Log\LoggerAwareTrait;
use Symfony\Component\Process\Process as BaseProcess;

class PowerProcess extends BaseProcess {

    use LoggerAwareTrait;

    /**
     * @param null $callback
     * @return int
     */
    public function run($callback = null)
    {
        return parent::run($callback); // TODO: Change the autogenerated stub
    }

}