<?php

/**
 * @file devshop_projects.module
 * a module in the DevShop module group which enables the user to create 
 * proects and group sites/platforms into project groups.
 */

/**
 * Implementation of hook_perm()
 */
function devshop_testing_perm() {
  return array(
    'create test task',
  );
}

/**
 * Implements hook_nodeapi()
 */
function devshop_testing_nodeapi(&$node, $op, $a3 = null) {

  if ($node->type != 'project' || $a3 != null) {
    return;
  }

  switch ($op) {
  case 'load':
    $data = db_fetch_array(db_query("SELECT tests_to_run " .
				     "FROM {hosting_devshop_project_testing} ".
				     "WHERE project_nid = %d", $node->nid));
    return $data;

  case 'view':

    break;


  case 'insert':
  case 'update':
    db_query("DELETE FROM {hosting_devshop_project_testing} " .
	     "WHERE project_nid = %d", $node->nid);

    db_query("INSERT INTO {hosting_devshop_project_testing} " .
	     "(project_nid, tests_to_run) " .
	     "VALUES(%d, '%s')", $node->nid, $node->tests_to_run);
    break;

  case 'delete':
    db_query("DELETE FROM {hosting_devshop_project_testing} " .
	     "WHERE project_nid = %d", $node->nid);
    break;

  default:
    break;
  }

}

/**
 * Implementation of hook_hosting_tasks()
 *
 */
function devshop_testing_hosting_tasks() {
  $tasks = array();

  $tasks['site']['test'] = array(
    'title' => t('Run Tests'),
    'description' => t('Run tests on the site.'),
    'dialog' => TRUE,
    'task_permitted' => TRUE,
    'access callback' => 'devshop_hosting_task_menu_access',
  );

  return $tasks;
}

/**
 * Implements hook_devshop_environment_actions().
 *
 * Defines the list of tasks that appear under the gear icon.
 */
function devshop_testing_devshop_environment_actions($environment) {
  return array(
    'test'
  );
}
/**
 * Implementation of hook_hosting_task_TASK_TYPE_form().
 *
 * Our parameters are added in devshop_testing_form_alter()
 */
function hosting_task_test_form($node) {

  $form = array();
  return $form;
}

/**
 * Implements hook_form_alter().
 */
function devshop_testing_form_alter(&$form, &$form_state, $form_id) {

  // If it's the project form, it's "defaults" for environments.
  if ($form_id == 'project_node_form') {
    $form['project']['settings']['testing'] = array(
      '#type' => 'fieldset',
      '#title' => t('Testing'),
      '#description' => t('Set the default testing settings for environments here.  Each environment can override these settings.'),
    );
    $testing_form = &$form['project']['settings']['testing'];
    $settings =  $form['#node']->project->settings;
  }

  // If it's the site (environment) form, it is the override.
  elseif ($form_id == 'site_node_form') {
    if (!isset($form['#node']->project)) {
      return;
    }
    $form['environment']['settings']['testing'] = array(
      '#type' => 'fieldset',
      '#title' => t('Testing'),
      '#description' => t('Set the testing settings for this environment.'),
      '#weight' => 100,
    );
    $testing_form = &$form['environment']['settings']['testing'];
    $settings =  $form['#node']->environment->settings;
  }
  elseif ($form_id == 'hosting_task_confirm_form') {
    $testing_form = &$form['parameters'];
    $node = node_load($form['nid']['#value']);
    $settings =  $node->environment->settings;
  }
  else {
    return;
  }

  // Setting defaults.  Use project settings if there are any.
  if (!isset($settings->testing)) {
    if (isset($form['#node']->project->settings->testing)) {
      $settings->testing = $form['#node']->project->settings->testing;
    }
    else {
      $settings->testing = array(
        'test_type' => 0,
        'tests_to_run' => '',
        'path_to_behat' => '',
      );
    }
  }
  $testing_form['test_type'] = array(
    '#title' => t('Test Type'),
    '#options' => array(
      0 => t('None'),
      'simpletest' => t('SimpleTest'),
      'behat' => t('Behat'),
    ),
    '#type' => 'radios',
    '#default_value' => $settings->testing['test_type'],
  );

  $testing_form['tests_to_run'] = array(
    '#type' => 'textarea',
    '#title' => t('Tests to Run'),
    '#default_value' => $settings->testing['tests_to_run'],
    '#rows' => 6,
    '#description' => t('Enter the names of the tests to run, one per line.  See the !link for examples, or call <strong><code>drush @@site test-run</code></strong> for a list of available tests.', array('!link' => l(t('Drupal API'), 'http://api.drupal.org/api/drupal/modules%21simpletest%21drupal_web_test_case.php/class/hierarchy/DrupalWebTestCase/7'), '@site' => 'drushalias')),
  );

  $testing_form['path_to_behat_bin'] = array(
    '#type' => 'textfield',
    '#title' => t('Path to Behat Binary'),
    '#description' => t('Enter the path to your bin/behat executable file. If relative, enter the path relative to the git repo root.'),
    '#default_value' => $settings->testing['path_to_behat'],
  );
  $testing_form['path_to_behat_tests'] = array(
    '#type' => 'textfield',
    '#title' => t('Path to Behat Tests'),
    '#description' => t('Enter the path to your tests (the *.featurefiles), relative to the git repo root.'),
    '#default_value' => $settings->testing['path_to_behat'],
  );

}