<?php

require_once 'vendor/autoload.php';
use Symfony\Component\Yaml\Parser;
use Symfony\Component\Process\Process;
use Symfony\Component\Process\Exception\ProcessFailedException;

/**
 * Implements hook_nodeapi_site_load()
 *
 * For site nodes, look for a .hooks file in the git repo root.
 */
function devshop_dothooks_devshop_environment_alter(&$environment) {
    $yaml = new Parser();
    $hooks_path = $environment->repo_root . '/.hooks';
    $environment->dothooks = $yaml->parse(file_get_contents($hooks_path));
}

/**
 * Runs a hook for a task.
 * @param $hook
 * @param $task
 */
function devshop_dothooks_run_hook($hook, $environment) {

  if (empty($environment->dothooks[$hook])) {
    drush_log('[.hooks] Hook not found: ' . $hook, 'info');
    return;
  }

  drush_log('[.hooks] Hook found: ' . $hook, 'ok');
  drush_log($environment->dothooks[$hook], 'dothooks_command');

  $process = new Process($environment->dothooks['verify']);
  $process->run(function ($type, $buffer) {
    if (Process::ERR === $type) {
      drush_log($buffer, 'dothooks_error');
      drush_log('[.hooks] Hook failed: ' . $buffer, 'error');
    } else {
      drush_log($buffer, 'dothooks_ok');
    }
  });
}

/**
 * Implements hook_preprocess_node()
 * for task nodes, show the .hooks output.
 * @param $vars
 */
function devshop_dothooks_preprocess_node(&$vars) {

  if ($vars['type'] == 'task') {
    $ref = node_load($vars['rid']);
    if ($ref->type == 'site' && $ref->environment->dothooks) {
      $messages = array();
      $i = 0;

      $query = db_query("SELECT message, type FROM {hosting_task_log} WHERE vid = %d AND type LIKE 'dothooks_%' ORDER BY vid, lid", $vars['node']->vid);
      while ($results = db_fetch_object($query)) {

        if ($results->type == 'dothooks_command') {
          $command = $results->message;
          $commands = explode("\n", $command);
          $i = 0;
          continue;
        }
        elseif ($results->type == 'dothooks_ok') {
          $status = 'success';
          $command = $commands[$i];
          $i++;
        }
        elseif ($results->type == 'dothooks_error') {
          $status = 'danger';
          $command = $commands[$i];
          $i++;
        }
        $output = $results->message;
        $messages[] = <<<HTML
<div class="panel panel-$status">
  <div class="panel-heading">$command</div>
  <div class="panel-body">
     <pre>$output</pre>
  </div>
</div>
HTML;
      }

      if (count($messages)) {
        $messages = implode("\n", $messages);
        $vars['task_well'] = <<<HTML
  <h3>Hooks Output</h3>
  <p>Loaded from the <samp>.hooks</samp> file.</p>
  $messages
HTML;

      }
    }
  }
}

/**
 * Implementation of hook_post_hosting_TASK_TYPE_task()
 * for Verify tasks.
 *
 * Runs the "verify" dotHook
 */
function devshop_dothooks_post_hosting_verify_task($task, $data) {
  devshop_dothooks_run_hook('verify', $task->ref->environment);
}