<?php

use DigitalOceanV2\Adapter\BuzzAdapter;
use DigitalOceanV2\DigitalOceanV2;

/**
 * Implements hook_menu()
 */
function devshop_digital_ocean_menu(){
  $items = array();
  $items['admin/hosting/devshop/digital_ocean'] = array(
    'title' => 'Digital Ocean',
    'description' => 'Retrieve options from Digital Ocean.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devshop_digital_ocean_options_form'),
    'access arguments' => array('administer devshop cloud'),
    'file' => 'options.php',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}
/**
 * Implements hook_hosting_service()
 */
function devshop_digital_ocean_hosting_service() {
  return array(
    'digital_ocean' => 'provider',
  );
}

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * Alters devshop cloud settings form to add digital_ocean api keys.
 */
function devshop_digital_ocean_form_devshop_cloud_settings_form_alter(&$form, &$form_state) {

  $form['digital_ocean'] = array(
    '#type' => 'fieldset',
    '#title' => t('Digital Ocean'),
    '#weight' => -100,
  );

  $form['digital_ocean']['devshop_cloud_digital_ocean_api_token'] = array(
    '#type' => 'textfield',
    '#title' => t('API token'),
    '#description' => t('Enter your digital_ocean username here.'),
    '#default_value' => variable_get('devshop_cloud_digital_ocean_api_token', ''),
  );

}

function devshop_digital_ocean_load_api(){
  require_once dirname(__FILE__) . '/digital-ocean-master/vendor/autoload.php';
  require_once dirname(__FILE__) . '/digital-ocean-master/src/DigitalOceanV2.php';
  $api_token = variable_get('devshop_cloud_digital_ocean_api_token', array());

  $adapter = new BuzzAdapter($api_token);
  $digitalocean = new DigitalOceanV2($adapter);
  return $digitalocean;
}

/**
 * Implementation of hook_nodeapi()
 */
function devshop_digital_ocean_nodeapi_server_load(&$node) {
  return array('digital_ocean_token' => variable_get('devshop_cloud_digital_ocean_api_token', array()));
}