name: Composer Validate & Install

on: [push]

jobs:
  build:

    runs-on: [ubuntu-16.04]

    steps:
    - uses: actions/checkout@v1

    - name: Cache composer vendor directory
      uses: actions/cache@v1
      with:
        path: vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Cache composer cache directory
      uses: actions/cache@v1
      with:
        path: ${HOME}/.composer
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
